import { links, services, barbers, plans, testimonials, units } from "../data/content.js";
const $=(s,scope=document)=>scope.querySelector(s);const $$=(s,scope=document)=>Array.from(scope.querySelectorAll(s));
function applyLinks(){$$("[data-link]").forEach(el=>{const key=el.dataset.link;if(links[key]){el.setAttribute("href",links[key]);el.setAttribute("target","_blank");el.setAttribute("rel","noopener noreferrer")}})}
function renderServices(){const grid=$("#servicesGrid");grid.innerHTML=services.map(service=>`<article class="service-card reveal"><img src="${service.image}" alt="${service.title}" loading="lazy"><div class="card-body"><span class="card-category">${service.category}</span><h3 class="card-title">${service.title}</h3><div class="meta-row"><strong>${service.price}</strong><span>${service.duration}</span></div><p class="card-copy">${service.description}</p><a class="card-link" data-link="appBarber" href="#">${service.cta} →</a></div></article>`).join("")}
function renderBarbers(){const track=$("#barbersTrack");track.innerHTML=barbers.map(barber=>`<article class="barber-card reveal"><span class="highlight">${barber.highlight}</span><img src="${barber.image}" alt="${barber.name}" loading="lazy"><div class="barber-info"><h3 class="card-title">${barber.name}</h3><p class="card-copy">${barber.specialty}</p><div class="tag-row">${barber.tags.map(tag=>`<span>${tag}</span>`).join("")}</div><a class="card-link" data-link="appBarber" href="#">Agendar com ${barber.name.split(" ")[0]} →</a></div></article>`).join("")}
function renderPlans(){const grid=$("#plansGrid");grid.innerHTML=plans.map(plan=>`<article class="plan-card reveal ${plan.featured?"featured":""}"><h3 class="card-title">${plan.name}</h3><div class="plan-price">${plan.price}</div><p class="card-copy">${plan.description}</p><ul>${plan.features.map(feature=>`<li>${feature}</li>`).join("")}</ul><a class="card-link" data-link="appBarber" href="#">Assinar pelo app →</a></article>`).join("")}
function renderTestimonials(){const grid=$("#testimonialsGrid");grid.innerHTML=testimonials.map(t=>`<article class="testimonial-card reveal"><strong>${t.name}</strong><p>“${t.text}”</p></article>`).join("")}
function renderUnits(){const grid=$("#unitsGrid");grid.innerHTML=units.map(unit=>`<article class="unit-card reveal"><span class="card-category">Unidade demo</span><h3 class="card-title">${unit.name}</h3><p class="card-copy">${unit.address}</p><p class="card-copy">${unit.hours}</p><a class="card-link" data-link="appBarber" href="#">Agendar nessa unidade →</a><br><a class="card-link" href="${unit.map}" target="_blank" rel="noopener noreferrer">Como chegar →</a></article>`).join("")}
function renderBookingChoices(){const serviceChoices=$("#serviceChoices");const barberChoices=$("#barberChoices");serviceChoices.innerHTML=["Corte","Barba","Combo","Planos"].map((item,index)=>`<button class="choice ${index===0?"selected":""}" data-next-step="2">${item}</button>`).join("");barberChoices.innerHTML=barbers.slice(0,4).map((barber,index)=>`<button class="choice ${index===0?"selected":""}" data-next-step="3">${barber.name.split(" ")[0]}</button>`).join("")}
function setupBookingSteps(){$$(".choice[data-next-step]").forEach(button=>{button.addEventListener("click",()=>{const parent=button.closest(".choice-grid");$$(".choice",parent).forEach(item=>item.classList.remove("selected"));button.classList.add("selected");const nextStep=button.dataset.nextStep;setTimeout(()=>{$$(".booking-step").forEach(step=>step.classList.remove("active"));$(`.booking-step[data-step="${nextStep}"]`).classList.add("active")},180)})})}
function setupHeader(){const header=$("#siteHeader");const progress=$("#scrollProgress");window.addEventListener("scroll",()=>{const scrollTop=window.scrollY;const docHeight=document.body.scrollHeight-window.innerHeight;const progressWidth=docHeight>0?(scrollTop/docHeight)*100:0;header.classList.toggle("is-scrolled",scrollTop>40);progress.style.width=`${progressWidth}%`},{passive:true})}
function setupSmoothScroll(){if(!window.Lenis)return;const lenis=new Lenis({duration:1.08,smoothWheel:true,wheelMultiplier:.85});function raf(time){lenis.raf(time);requestAnimationFrame(raf)}requestAnimationFrame(raf)}
function setupAnimations(){if(!window.gsap||!window.ScrollTrigger){$$(".reveal").forEach(el=>{el.style.opacity=1;el.style.transform="none"});return}gsap.registerPlugin(ScrollTrigger);gsap.to(".preloader img",{scale:1.04,duration:.9,repeat:-1,yoyo:true,ease:"power1.inOut"});gsap.utils.toArray(".reveal").forEach(el=>{gsap.to(el,{opacity:1,y:0,duration:.85,ease:"power3.out",scrollTrigger:{trigger:el,start:"top 86%"}})});gsap.to(".hero-media img, .hero-video",{yPercent:12,ease:"none",scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:true}});gsap.utils.toArray(".parallax-img").forEach(img=>{gsap.fromTo(img,{y:42},{y:-28,ease:"none",scrollTrigger:{trigger:img,start:"top bottom",end:"bottom top",scrub:true}})});gsap.utils.toArray(".magnetic").forEach(el=>{el.addEventListener("mousemove",event=>{const rect=el.getBoundingClientRect();const x=event.clientX-rect.left-rect.width/2;const y=event.clientY-rect.top-rect.height/2;gsap.to(el,{x:x*.12,y:y*.18,duration:.35,ease:"power3.out"})});el.addEventListener("mouseleave",()=>{gsap.to(el,{x:0,y:0,duration:.55,ease:"elastic.out(1, .4)"})})})}
function setupPreloader(){const preloader=$("#preloader");window.addEventListener("load",()=>{setTimeout(()=>preloader.classList.add("is-hidden"),550)})}
function init(){renderServices();renderBarbers();renderPlans();renderTestimonials();renderUnits();renderBookingChoices();applyLinks();setupBookingSteps();setupHeader();setupSmoothScroll();setupAnimations();setupPreloader()}init();
